### ISSUE TITLE
check background information on readme

### ISSUE THREAD

**Issue by stg7** [Telecommunication-Telemedia-Assessment/SITI#10]

**Comment by rimede** [comment]
I can't compile on Ubuntu 20.04. I believe they are compatibility problems between packages. I tried some solutions, but I was not successful.

Erro: "No package 'opencv' found
OSError: 'pkg-config --libs opencv' exited 1:
  File "/home/rebelde64/Downloads/SITI/src/SITI/SConstruct", line 13:
    env.ParseConfig('pkg-config --libs opencv')  # static build does not work anymore with default opencv ubuntu package
  File "/usr/lib/scons/SCons/Environment.py", line 1578:
    return function(self, self.backtick(command))
  File "/usr/lib/scons/SCons/Environment.py", line 589:
    raise OSError("'%s' exited %d" % (command, status))
"

Can you suggest a solution?
