### ISSUE TITLE
The Python script generates incorrect results

### ISSUE THREAD

**Issue by henriquedgarcia** [Telecommunication-Telemedia-Assessment/SITI#11]
Hello guys. For a college work I compared the result of the python script with the result of the program with OpenCV and the results are different. I basically found three errors:
- Processing must be done only in the luminance channel;
- The arrays used are of type UINT8 that do not represent the results of the operations correctly;
- The default options of the Sobel filter of the SciPy package do not detect the edges correctly.

I would like to contribute your code. I'll do a pull request with the fixes.

Thanks.

**Comment by slhck** [comment]
We'd love to see a pull request if you have proposed changes. By writing OpenCV, do you have a reference code available? What specifically are the issues with the last two points you've mentioned?

**Comment by henriquedgarcia** [comment]
Hi. Sorry for my English. The changes I made were in the Python script only.
The skvideo.io.vreader () function with the "as_grey = True" option returns an ndarray of the shape (1, height, width, 1) and dtype uint8. The frame subtraction some times generates negative numbers that type uint8 can not represent. The sobel filter also generates numbers larger than 255. So I applied a reshape to (height, width) and changed the dtype to float32.

**Comment by slhck** [comment]
Thanks a lot for the explanation! I've learned something from that. I will do a merge and release a new version soon.

**Comment by henriquedgarcia** [comment]
You're welcome. It's good to have contributed.

**Comment by slhck** [comment]
By the way, I made a new release for my own SITI implementation that now uses the same corrected calculations based on your proposal: https://github.com/slhck/siti — so thank you for those! (I am not sure if you were aware of the other Python-only tool.)

**Comment by henriquedgarcia** [comment]
You're welcome. I had already seen his module in the pip, but did not know it was the same code. Thanks for the information.

**Comment by slhck** [comment]
It's not the same code, actually. It's a different program that was written before the Python wrapper in this repository, I believe.
