### ISSUE TITLE
It is not compiling.

### ISSUE THREAD

**Issue by rimede** [Telecommunication-Telemedia-Assessment/SITI#13]
I can't compile on Ubuntu 20.04. I believe they are compatibility problems between packages. I tried some solutions, but I was not successful.

Erro: "No package 'opencv' found
OSError: 'pkg-config --libs opencv' exited 1:
File "/home/rebelde64/Downloads/SITI/src/SITI/SConstruct", line 13:
env.ParseConfig('pkg-config --libs opencv') # static build does not work anymore with default opencv ubuntu package
File "/usr/lib/scons/SCons/Environment.py", line 1578:
return function(self, self.backtick(command))
File "/usr/lib/scons/SCons/Environment.py", line 589:
raise OSError("'%s' exited %d" % (command, status))"

Can you suggest a solution?

**Comment by slhck** [comment]
Have you installed OpenCV according to the requirements?

    apt-get install libopencv-dev

Just asking to get the complete picture. Could be that this changed in 20.04, and the scripts have to be revisited.

**Comment by rimede** [comment]
Yes, I have this version installed: libopencv-dev is already the newest version (4.2.0 + dfsg-5)

**Comment by plebreton** [comment]
I will have a look.

It is most likely the scons related files which need to be updated for opencv 4.

OpenCV 4 removed some old API, so they made sure you don't use the version 4 inadvertently. I think opencv should become opencv4 in the package config command.

You can also just install opencv 3.x.x which should work out of the box

**Comment by stg7** [comment]
maybe the branch opencv4-check solves it? (it is at least working for me, however i didn't checked if it produces the identical values, and if it still works under windows)

**Comment by slhck** [comment]
@stg7 Building works for me under Ubuntu 20.04 too now.

I get slightly different values than with my Python implementation, but this could also have been an old issue.

But if we move it to OpenCV 4 (shipped with 20.04), then it will not work anymore with 18.04, correct?

**Comment by plebreton** [comment]
Yeah, the numerical differences with the python version are not new. 
I am not sure exactly why.
