### ISSUE TITLE
Doesn't output text

### ISSUE THREAD

**Issue by bael94** [Telecommunication-Telemedia-Assessment/SITI#21]
The results in terminal aren't text type, and doesn't get saved to txt files.

**Comment by slhck** [comment]
I am not sure what you mean by that. Please show which commands you ran, what you expected, and what output you got instead.

Note that this C++/OpenCV version is basically deprecated. This repository contains a [Python script](https://github.com/Telecommunication-Telemedia-Assessment/SITI/tree/master/python) which however does not output fully conformant values.

You can find a more recent Python CLI version [here](https://github.com/slhck/siti), or a Python library version [here](https://github.com/Telecommunication-Telemedia-Assessment/siti-tools).

**Comment by bael94** [comment]
SITI -i input ... > analysis.txt
The txt file is returned empty eventhough the analysis results are printed in shell.
I also tried also via python's subprocess, and the output of the process is always empty.

**Comment by slhck** [comment]
With the C++ version, the output is written to stderr. Please use `2> analysis.txt`.

Alternatively, with the Python implementation from [here](https://github.com/slhck/siti), it writes to stdout: 

```
siti /path/to/file.mp4 -of csv > output.csv 
```

**Comment by bael94** [comment]
Oh super, yes it works now.
I'll also try using the python implementation.
Thanks
