### ISSUE TITLE
Update code to use Transparent API / OpenCL

### ISSUE THREAD

**Issue by plebreton** [Telecommunication-Telemedia-Assessment/SITI#5]
I made a slightly different version of the code using the T-API and built-in functions to compute sobel filters, gradient, and std on GPU using OpenCL. Basically it looks like that: 

`

		cv::UMat gx, gy, grad;
		cv::Sobel(frame1, gx, CV_32F, 1, 0, 3, 1, 0, cv::BORDER_DEFAULT);
		cv::Sobel(frame1, gy, CV_32F, 0, 1, 3, 1, 0, cv::BORDER_DEFAULT);
		cv::add(gx.mul(gx), gy.mul(gy), grad);
		cv::sqrt(grad, grad);

		cv::Scalar meanSp, stddevSp;
		cv::meanStdDev(grad, meanSp, stddevSp, maskValidSobel);

		maxSI = std::max(maxSI, stddevSp.val[0]);
		minSI = std::min(minSI, stddevSp.val[0]);

		cv::UMat dt;
		cv::subtract(frame1, frame2, dt);

		cv::Scalar meanT, stddevT;
		cv::meanStdDev(dt, meanT, stddevT, maskValidSobel);

		maxTI = std::max(maxTI, stddevT.val[0]);
		minTI = std::min(minTI, stddevT.val[0]);

 `

And the code:

[main.txt](https://github.com/Telecommunication-Telemedia-Assessment/SITI/files/1900939/main.txt)

I did not really push it as the numeric values differs a bit (in the range of 0.1 ). But it run faster mostly if you use high resolution and read videos from a compressed format (so not, YUV where the speed is mostly limited by disk access). 

So I was not fully sure if we push it or not...

**Comment by slhck** [comment]
In my opinion it would be fine to push it, if it increases speed and leads to *roughly* the same values. At least in terms of definition it seems correct?

Generally, it's a bit of a pity that there are no good test vectors around. I made this other implementation of SITI in Python and have to check if I get the same values; I'm using the `sobel` filter from Scipy there and it seems that the `magnitude`-based approach is equivalent to your calculations:

https://github.com/slhck/siti/blob/master/siti/__main__.py#L61

(Here, `np.hypot` is equivalent to `sqrt(x^2 + y^2)`)

**Comment by MWijnants-1** [comment]
I made a C++ implementation myself a few years ago, and I'm getting identical SI / TI results as with this implementation.

**Comment by plebreton** [comment]
I pushed that version
