### ISSUE TITLE
Outer set of pixels (i.e., rows 0 and height-1, columns 0 and width-1) are excluded from TI calculation.

### ISSUE THREAD

**Issue by MWijnants-1** [Telecommunication-Telemedia-Assessment/SITI#7]
I have a pull request ready to fix this issue; can only be applied as soon as pull request #6 has been incorporated.

**Comment by slhck** [comment]
Sure, let's see, I haven't written the original code, so I would pass on to @plebreton — what do you think about #6 and this?

**Comment by plebreton** [comment]
It is now handled.
