### ISSUE TITLE
SI TI tool

### ISSUE THREAD

**Issue by jasa23** [Telecommunication-Telemedia-Assessment/SITI#9]
Hi,
i have some videos that i want to calculate their SI & TI 
 i followed the steps but there is nothing that appears after running
I would like to know in which directoy should I put the video test?
thanks

**Comment by slhck** [comment]
Please show which exact command you were trying. Thanks!

**Comment by jasa23** [comment]
I want to run this tool: https://github.com/Telecommunication-Telemedia-Assessment/SITI
to calculate SI & TI for this video: akiyo_cif.yuv

**Comment by slhck** [comment]
Yes, how did you run the SITI program, that is, which exact command did you enter in the command line, and what output did you get?

**Comment by sarakhalfa** [comment]
sorry, but Yes, how did you run the SITI program, that is, which exact command did you enter in the command line, and what output did you get?

**Comment by jasa23** [comment]
sorry, I execute it by double clicking on the executable file
do I have to use visual studio for that?
i didn't use any command
i don't know how to do

**Comment by jasa23** [comment]
@slhck i work under windows 2007

**Comment by slhck** [comment]
Oh, I understand now. You have to open a shell in the folder where the executable is saved, and call it from a command prompt.

**Comment by jasa23** [comment]
please how to open a shell in the folder?
sorry i'm new in this domain
thanks

**Comment by slhck** [comment]
Please refer to tutorials in which you may find information on how to open a command line prompt and execute a command. We unfortunately cannot give support for general Windows usage. 

An example can be found here: https://www.lifewire.com/how-to-open-command-prompt-2618089

If you have a specific problem with this tool, feel free to ask.

**Comment by jasa23** [comment]
@slhck thank you for everything
